# Generated by Django 5.0.6 on 2024-06-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('state', models.CharField(default='InProgress', max_length=10)),
                ('incorrect_guesses', models.IntegerField(default=0)),
                ('max_incorrect_guesses', models.IntegerField()),
                ('guessed_letters', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
